In [1]:
import importlib
import frengression
# importlib.reload(frengression)
from data_causl.utils import *
from data_causl.data import *
from frengression import *

device = torch.device('cpu')
from CausalEGM import *

import numpy as np
import jax.numpy as jnp
import pickle
import os
from tqdm import tqdm
import src.exp_utils as exp_utils

from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import log_loss
from scipy.spatial.distance import pdist, squareform
import warnings

warnings.filterwarnings("ignore")


In [10]:
s, x,z,y= generate_data_survivl(n=200,T=3)

In [11]:
s = torch.tensor(s, dtype=torch.float32)
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
z = torch.tensor(z, dtype=torch.float32)

In [12]:
model = FrengressionSeq(x_dim=1, y_dim=1, z_dim=1, T=3, s_dim = 1, noise_dim=10, num_layer=3, hidden_dim=100, device=device, x_binary = False)

In [13]:
model.train_xz(x=x, z=z, y=y, s=s, num_iters=6000, lr=1e-3, print_every_iter=1000)

Epoch 1: loss 2.4804, loss1 2.6083, loss2 0.2560
Epoch 1000: loss 0.3465, loss1 0.9379, loss2 1.1829
Epoch 2000: loss 0.3142, loss1 0.7094, loss2 0.7905
Epoch 3000: loss 0.3933, loss1 0.7512, loss2 0.7157
Epoch 4000: loss 0.2981, loss1 0.7624, loss2 0.9284
Epoch 5000: loss 0.1284, loss1 0.6350, loss2 1.0131
Epoch 6000: loss 0.2008, loss1 0.6150, loss2 0.8285


In [16]:
x

tensor([[0.5512, 0.3997, 0.2428],
        [1.7757, 0.6578, 1.5665],
        [2.0281, 0.5227, 0.2144],
        [1.3850, 0.3478, 0.9146],
        [0.3300, 0.6243, 1.7378],
        [0.1655, 0.7407, 1.2524],
        [0.9873, 0.6735, 0.9293],
        [1.4977, 2.7731, 0.1718],
        [0.6125, 1.1733, 1.4671],
        [0.6384, 0.7565, 0.8637]])

tensor([[ 0.5512, -1.8793,  0.8042],
        [ 1.7757, -1.2392,  0.0764],
        [ 2.0281,  1.1604,  1.0271],
        [ 1.3850,  0.0037,  1.7708],
        [ 0.3300, -0.0955, -0.4577],
        [ 0.1655,  1.7956,  1.3170],
        [ 0.9873, -1.3221, -0.3142],
        [ 1.4977, -0.2761, -0.4942],
        [ 0.6125, -0.7440, -0.0250],
        [ 0.6384, -1.0701, -0.8644]])

In [14]:
x[:,]

tensor([0.2428, 1.5665, 0.2144, 0.9146, 1.7378, 1.2524, 0.9293, 0.1718, 1.4671,
        0.8637])