In [1]:
import importlib
import frengression
# importlib.reload(frengression)
from data_causl.utils import *
from data_causl.data import *
from frengression import *

device = torch.device('cpu')
from CausalEGM import *

import numpy as np
import jax.numpy as jnp
import pickle
import os
from tqdm import tqdm
import src.exp_utils as exp_utils

from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import log_loss
from scipy.spatial.distance import pdist, squareform
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
generate_data_survivl()

([array([[0.55123124],
         [1.7757418 ],
         [2.02810734],
         [1.38503609],
         [0.32997968],
         [0.16546242],
         [0.98727616],
         [1.49767916],
         [0.61248812],
         [0.63835405]]),
  array([[0.39974643],
         [0.65782047],
         [0.52274829],
         [0.34780225],
         [0.62425586],
         [0.74066732],
         [0.67345895],
         [2.77307906],
         [1.1733023 ],
         [0.75646761]]),
  array([[0.24276823],
         [1.56649561],
         [0.21441252],
         [0.91458817],
         [1.73776431],
         [1.25243931],
         [0.92934182],
         [0.17175609],
         [1.46713891],
         [0.86372554]]),
  array([[3.46412995],
         [2.26714733],
         [0.96820074],
         [0.99838752],
         [0.90000955],
         [2.78068083],
         [0.33807155],
         [0.34322305],
         [1.27415974],
         [0.68408022]]),
  array([[0.04151631],
         [0.48526089],
         [0.18929261],
   